project:
  type: website
  output-dir: docs

website:
  title: "SciK-Health"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: The Project
        href: theProject.qmd
      - text: Research Team
        href: team.qmd
      - text: Data
        href: data.qmd
      - text: Outputs
        href: outputs.qmd
      - text: Contact
        href: contact.qmd
format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

