project:
  type: website
  output-dir: docs

website:
  title: "Sci K-Health"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: theProject.qmd
        text: The Project
      - href: researchGroup.qmd
        text: Research Group
      - href: scientificProducts.qmd
        text: Scientific Products

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

