project:
  type: website
  output-dir: docs

website:
  title: "SciK-Health"
  navbar:
    left:
      - text: The Project
        href: theProject.qmd
      - text: Research Team
        href: team.qmd
      - text: Data
        href: data.qmd
      - text: Scientific Products
        menu:
        - text: Project References
          href: references.qmd
        - text: Publications
          href: publications.qmd
        - text: Conferences
          href: conferences.qmd
format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

